### ISSUE TITLE
/usr/bin/gswitch: line 57: [: too many arguments

### ISSUE THREAD

**Issue by TechKnowCase** [karli-sjoberg/gswitch#13] opened 2020-10-01 14:52 UTC
Hey,

Basically, if I echo $XORG_DRIVER right before the if statement, I always have more than just "nvidia", for example:
"nvidia Driver"
"nouveau ... nvidia"
"nvidia nvidia modesetting"
"kbd mouse nvidia"

i'm no programmer, but this might fix the issue: https://stackoverflow.com/questions/229551/how-to-check-if-a-string-contains-a-substring-in-bash

Thank you for the great code!

**Comment by karli-sjoberg** [comment] 2020-10-06 05:14
Hm, what does your "/etc/X11/xorg.conf.egpu" look like?

**Comment by TechKnowCase** [comment] 2020-10-11 09:05
# nvidia-settings: X configuration file generated by nvidia-settings
# nvidia-settings:  version 455.23.04


#Section "ServerLayout"
#    Identifier     "Default Layout"
#    Screen      0  "Screen0" 0 0
#    InputDevice    "Keyboard0" "CoreKeyboard"
#    InputDevice    "Mouse0" "CorePointer"
#    Option         "Xinerama" "0"
#EndSection

#Section "Module"
#    Load           "modesetting"
#EndSection

#Section "InputDevice"
#
#    # generated from default
#    Identifier     "Keyboard0"
#    Driver         "kbd"
#EndSection

#Section "InputDevice"
#
#    # generated from default
#    Identifier     "Mouse0"
#    Driver         "mouse"
#    Option         "Protocol" "auto"
#    Option         "Device" "/dev/psaux"
#    Option         "Emulate3Buttons" "no"
#    Option         "ZAxisMapping" "4 5"
#EndSection

Section "Monitor"
    Identifier     "Monitor0"
    VendorName     "Unknown"
#    ModelName      "Acer GN246HL"
#    HorizSync       30.0 - 160.0
#    VertRefresh     56.0 - 144.0
EndSection

Section "Device"
    Identifier     "Device0"
    Driver         "nvidia"
    VendorName     "NVIDIA Corporation"
    BoardName      "GeForce GTX 1080"
    Option         "AllowEmptyInitialConfiguration"
    Option         "AllowExternalGpus" "True"
    BusID          "PCI:3D:0:0"
EndSection

Section "Screen"
    Identifier     "Default Screen"
    Device         "Device0"
    Monitor        "Monitor0"
EndSection

#Section "Screen"

# Removed Option "metamodes" "DVI-D-0: 1920x1080_144 +1920+0 {ForceCompositionPipeline=On, ForceFullCompositionPipeline=On}, HDMI-0: 1920x1080_60 +0+0, DP-3: 1024x768_60 +3840+312"
#    Identifier     "Screen0"
#    Device         "Device0"
#    Monitor        "Monitor0"
#    DefaultDepth    24
#    Option         "Stereo" "0"
#    Option         "nvidiaXineramaInfoOrder" "DFP-0"
#    Option         "metamodes" "DVI-D-0: 1920x1080_144 +1920+0 {ForceCompositionPipeline=On, ForceFullCompositionPipeline=On}, HDMI-0: 1920x1080_60 +0+0, DP-3: 1024x768_60 +3840+0"
#    Option         "SLI" "Off"
#    Option         "MultiGPU" "Off"
#    Option         "BaseMosaic" "off"
#    SubSection     "Display"
#        Depth       24
#    EndSubSection
#EndSection

**Comment by TechKnowCase** [comment] 2020-10-11 09:06
```
# nvidia-settings: X configuration file generated by nvidia-settings
# nvidia-settings:  version 455.23.04


#Section "ServerLayout"
#    Identifier     "Default Layout"
#    Screen      0  "Screen0" 0 0
#    InputDevice    "Keyboard0" "CoreKeyboard"
#    InputDevice    "Mouse0" "CorePointer"
#    Option         "Xinerama" "0"
#EndSection

#Section "Module"
#    Load           "modesetting"
#EndSection

#Section "InputDevice"
#
#    # generated from default
#    Identifier     "Keyboard0"
#    Driver         "kbd"
#EndSection

#Section "InputDevice"
#
#    # generated from default
#    Identifier     "Mouse0"
#    Driver         "mouse"
#    Option         "Protocol" "auto"
#    Option         "Device" "/dev/psaux"
#    Option         "Emulate3Buttons" "no"
#    Option         "ZAxisMapping" "4 5"
#EndSection

Section "Monitor"
    Identifier     "Monitor0"
    VendorName     "Unknown"
#    ModelName      "Acer GN246HL"
#    HorizSync       30.0 - 160.0
#    VertRefresh     56.0 - 144.0
EndSection

Section "Device"
    Identifier     "Device0"
    Driver         "nvidia"
    VendorName     "NVIDIA Corporation"
    BoardName      "GeForce GTX 1080"
    Option         "AllowEmptyInitialConfiguration"
    Option         "AllowExternalGpus" "True"
    BusID          "PCI:3D:0:0"
EndSection

Section "Screen"
    Identifier     "Default Screen"
    Device         "Device0"
    Monitor        "Monitor0"
EndSection

#Section "Screen"

# Removed Option "metamodes" "DVI-D-0: 1920x1080_144 +1920+0 {ForceCompositionPipeline=On, ForceFullCompositionPipeline=On}, HDMI-0: 1920x1080_60 +0+0, DP-3: 1024x768_60 +3840+312"
#    Identifier     "Screen0"
#    Device         "Device0"
#    Monitor        "Monitor0"
#    DefaultDepth    24
#    Option         "Stereo" "0"
#    Option         "nvidiaXineramaInfoOrder" "DFP-0"
#    Option         "metamodes" "DVI-D-0: 1920x1080_144 +1920+0 {ForceCompositionPipeline=On, ForceFullCompositionPipeline=On}, HDMI-0: 1920x1080_60 +0+0, DP-3: 1024x768_60 +3840+0"
#    Option         "SLI" "Off"
#    Option         "MultiGPU" "Off"
#    Option         "BaseMosaic" "off"
#    SubSection     "Display"
#        Depth       24
#    EndSubSection
#EndSection

```

**Comment by wbolster** [comment] 2021-04-07 22:16
this is just bad shell script syntax.

please run "shellcheck" on your script and fix all the warnings :wink:

**Comment by karli-sjoberg** [comment] 2021-04-08 08:59
Thanks for reporting, I'm closing this issue now.

**Closed as completed by karli-sjoberg** 2021-04-08 08:59 UTC

**Comment by wbolster** [comment] 2021-04-08 09:24
@karli-sjoberg, no the problem is in the `gswitch` shell script. try `shellcheck gswitch` and you'll see a ton of warnings/errors. this bug report is one of them.
